<?php

namespace PHPay\Asaas\Resources\Subscription\Interface;

use PHPay\Asaas\Enums\SubscriptionCycleEnum;
use PHPay\Support\{Customer as CustomerData, Money};

interface SubscriptionInterface
{
    /**
     * attach an existing gateway customer to the subscription.
     *
     * @param string $customerId
     * @return SubscriptionInterface
     */
    public function setCustomerId(string $customerId): SubscriptionInterface;

    /**
     * attach a customer to the subscription, reusing it when an id is given.
     *
     * @param array<mixed> $customer
     * @return SubscriptionInterface
     */
    public function setCustomer(CustomerData|array $customer): SubscriptionInterface;

    /**
     * set the payload of the subscription
     *
     * @param array<mixed> $subscription
     * @return SubscriptionInterface
     */
    public function setSubscription(array $subscription): SubscriptionInterface;

    /**
     * set the amount of each charge
     *
     * @param Money|int|float $amount
     * @return SubscriptionInterface
     */
    public function setAmount(Money|int|float $amount): SubscriptionInterface;

    /**
     * set how often a charge is generated
     *
     * @param SubscriptionCycleEnum $cycle
     * @return SubscriptionInterface
     */
    public function setCycle(SubscriptionCycleEnum $cycle): SubscriptionInterface;

    /**
     * set list filters
     *
     * @param array<mixed> $queryParams
     * @return SubscriptionInterface
     */
    public function setQueryParams(array $queryParams): SubscriptionInterface;

    /**
     * create subscription
     *
     * @param array<mixed> $subscription
     * @return array<mixed>
     */
    public function create(array $subscription = []): array;

    /**
     * list subscriptions
     *
     * @return array<mixed>
     */
    public function getAll(): array;

    /**
     * find a subscription
     *
     * @param string $id
     * @return array<mixed>
     */
    public function find(string $id): array;

    /**
     * update a subscription
     *
     * @param string $id
     * @param array<mixed> $data
     * @return array<mixed>
     */
    public function update(string $id, array $data): array;

    /**
     * stop generating charges, keeping the existing ones
     *
     * @param string $id
     * @return array<mixed>
     */
    public function deactivate(string $id): array;

    /**
     * generate charges again
     *
     * @param string $id
     * @param string $nextDueDate
     * @return array<mixed>
     */
    public function reactivate(string $id, string $nextDueDate): array;

    /**
     * remove a subscription
     *
     * @param string $id
     * @return bool
     */
    public function destroy(string $id): bool;

    /**
     * replace the card of a subscription without charging it
     *
     * @param string $id
     * @param array<mixed> $card
     * @return array<mixed>
     */
    public function updateCreditCard(string $id, array $card): array;

    /**
     * charges already generated by a subscription
     *
     * @param string $id
     * @param array<mixed> $filters
     * @return array<mixed>
     */
    public function getPayments(string $id, array $filters = []): array;

    /**
     * payment book (carnê) of a subscription, as a PDF
     *
     * @param string $id
     * @param int|null $month
     * @param int|null $year
     * @return string
     */
    public function paymentBook(string $id, ?int $month = null, ?int $year = null): string;

    /**
     * configure the invoice issued for each charge
     *
     * @param string $id
     * @param array<mixed> $settings
     * @return array<mixed>
     */
    public function createInvoiceSettings(string $id, array $settings): array;

    /**
     * find the invoice settings
     *
     * @param string $id
     * @return array<mixed>
     */
    public function getInvoiceSettings(string $id): array;

    /**
     * update the invoice settings
     *
     * @param string $id
     * @param array<mixed> $settings
     * @return array<mixed>
     */
    public function updateInvoiceSettings(string $id, array $settings): array;

    /**
     * remove the invoice settings
     *
     * @param string $id
     * @return bool
     */
    public function destroyInvoiceSettings(string $id): bool;

    /**
     * invoices issued for the charges of a subscription
     *
     * @param string $id
     * @param array<mixed> $filters
     * @return array<mixed>
     */
    public function getInvoices(string $id, array $filters = []): array;
}
